/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Challenge } from "./Challenge";
import { ChallengeCountArgs } from "./ChallengeCountArgs";
import { ChallengeFindManyArgs } from "./ChallengeFindManyArgs";
import { ChallengeFindUniqueArgs } from "./ChallengeFindUniqueArgs";
import { CreateChallengeArgs } from "./CreateChallengeArgs";
import { UpdateChallengeArgs } from "./UpdateChallengeArgs";
import { DeleteChallengeArgs } from "./DeleteChallengeArgs";
import { ChallengeService } from "../challenge.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Challenge)
export class ChallengeResolverBase {
  constructor(
    protected readonly service: ChallengeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Challenge",
    action: "read",
    possession: "any",
  })
  async _challengesMeta(
    @graphql.Args() args: ChallengeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Challenge])
  @nestAccessControl.UseRoles({
    resource: "Challenge",
    action: "read",
    possession: "any",
  })
  async challenges(
    @graphql.Args() args: ChallengeFindManyArgs
  ): Promise<Challenge[]> {
    return this.service.challenges(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Challenge, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Challenge",
    action: "read",
    possession: "own",
  })
  async challenge(
    @graphql.Args() args: ChallengeFindUniqueArgs
  ): Promise<Challenge | null> {
    const result = await this.service.challenge(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Challenge)
  @nestAccessControl.UseRoles({
    resource: "Challenge",
    action: "create",
    possession: "any",
  })
  async createChallenge(
    @graphql.Args() args: CreateChallengeArgs
  ): Promise<Challenge> {
    return await this.service.createChallenge({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Challenge)
  @nestAccessControl.UseRoles({
    resource: "Challenge",
    action: "update",
    possession: "any",
  })
  async updateChallenge(
    @graphql.Args() args: UpdateChallengeArgs
  ): Promise<Challenge | null> {
    try {
      return await this.service.updateChallenge({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Challenge)
  @nestAccessControl.UseRoles({
    resource: "Challenge",
    action: "delete",
    possession: "any",
  })
  async deleteChallenge(
    @graphql.Args() args: DeleteChallengeArgs
  ): Promise<Challenge | null> {
    try {
      return await this.service.deleteChallenge(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
