/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ChallengeService } from "../challenge.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ChallengeCreateInput } from "./ChallengeCreateInput";
import { Challenge } from "./Challenge";
import { ChallengeFindManyArgs } from "./ChallengeFindManyArgs";
import { ChallengeWhereUniqueInput } from "./ChallengeWhereUniqueInput";
import { ChallengeUpdateInput } from "./ChallengeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ChallengeControllerBase {
  constructor(
    protected readonly service: ChallengeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Challenge })
  @nestAccessControl.UseRoles({
    resource: "Challenge",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createChallenge(
    @common.Body() data: ChallengeCreateInput
  ): Promise<Challenge> {
    return await this.service.createChallenge({
      data: data,
      select: {
        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        participants: true,
        startDate: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Challenge] })
  @ApiNestedQuery(ChallengeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Challenge",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async challenges(@common.Req() request: Request): Promise<Challenge[]> {
    const args = plainToClass(ChallengeFindManyArgs, request.query);
    return this.service.challenges({
      ...args,
      select: {
        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        participants: true,
        startDate: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Challenge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Challenge",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async challenge(
    @common.Param() params: ChallengeWhereUniqueInput
  ): Promise<Challenge | null> {
    const result = await this.service.challenge({
      where: params,
      select: {
        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        participants: true,
        startDate: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Challenge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Challenge",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateChallenge(
    @common.Param() params: ChallengeWhereUniqueInput,
    @common.Body() data: ChallengeUpdateInput
  ): Promise<Challenge | null> {
    try {
      return await this.service.updateChallenge({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          endDate: true,
          id: true,
          participants: true,
          startDate: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Challenge })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Challenge",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteChallenge(
    @common.Param() params: ChallengeWhereUniqueInput
  ): Promise<Challenge | null> {
    try {
      return await this.service.deleteChallenge({
        where: params,
        select: {
          createdAt: true,
          description: true,
          endDate: true,
          id: true,
          participants: true,
          startDate: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
