/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Teacher as PrismaTeacher,
  Student as PrismaStudent,
} from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class TeacherServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(args: Omit<Prisma.TeacherCountArgs, "select">): Promise<number> {
    return this.prisma.teacher.count(args);
  }

  async teachers(args: Prisma.TeacherFindManyArgs): Promise<PrismaTeacher[]> {
    return this.prisma.teacher.findMany(args);
  }
  async teacher(
    args: Prisma.TeacherFindUniqueArgs
  ): Promise<PrismaTeacher | null> {
    return this.prisma.teacher.findUnique(args);
  }
  async createTeacher(args: Prisma.TeacherCreateArgs): Promise<PrismaTeacher> {
    return this.prisma.teacher.create(args);
  }
  async updateTeacher(args: Prisma.TeacherUpdateArgs): Promise<PrismaTeacher> {
    return this.prisma.teacher.update(args);
  }
  async deleteTeacher(args: Prisma.TeacherDeleteArgs): Promise<PrismaTeacher> {
    return this.prisma.teacher.delete(args);
  }

  async uploadProfilePicture<T extends Prisma.TeacherFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TeacherFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaTeacher> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "profilePicture";
    const profilePicture = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.teacher.update({
      where: args.where,

      data: {
        profilePicture: profilePicture as InputJsonValue,
      },
    });
  }

  async downloadProfilePicture<T extends Prisma.TeacherFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TeacherFindUniqueArgs>
  ): Promise<FileDownload> {
    const { profilePicture } = await this.prisma.teacher.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      profilePicture as unknown as LocalStorageFile
    );
  }

  async deleteProfilePicture<T extends Prisma.TeacherFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TeacherFindUniqueArgs>
  ): Promise<PrismaTeacher> {
    const { profilePicture } = await this.prisma.teacher.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      profilePicture as unknown as LocalStorageFile
    );

    return await this.prisma.teacher.update({
      where: args.where,

      data: {
        profilePicture: Prisma.DbNull,
      },
    });
  }

  async findStudents(
    parentId: string,
    args: Prisma.StudentFindManyArgs
  ): Promise<PrismaStudent[]> {
    return this.prisma.teacher
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .students(args);
  }
}
