/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { GraphQLUpload } from "graphql-upload";
import { FileUpload } from "src/storage/base/storage.types";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Teacher } from "./Teacher";
import { TeacherCountArgs } from "./TeacherCountArgs";
import { TeacherFindManyArgs } from "./TeacherFindManyArgs";
import { TeacherFindUniqueArgs } from "./TeacherFindUniqueArgs";
import { CreateTeacherArgs } from "./CreateTeacherArgs";
import { UpdateTeacherArgs } from "./UpdateTeacherArgs";
import { DeleteTeacherArgs } from "./DeleteTeacherArgs";
import { StudentFindManyArgs } from "../../student/base/StudentFindManyArgs";
import { Student } from "../../student/base/Student";
import { TeacherService } from "../teacher.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Teacher)
export class TeacherResolverBase {
  constructor(
    protected readonly service: TeacherService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "read",
    possession: "any",
  })
  async _teachersMeta(
    @graphql.Args() args: TeacherCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Teacher])
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "read",
    possession: "any",
  })
  async teachers(
    @graphql.Args() args: TeacherFindManyArgs
  ): Promise<Teacher[]> {
    return this.service.teachers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Teacher, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "read",
    possession: "own",
  })
  async teacher(
    @graphql.Args() args: TeacherFindUniqueArgs
  ): Promise<Teacher | null> {
    const result = await this.service.teacher(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Teacher)
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "create",
    possession: "any",
  })
  async createTeacher(
    @graphql.Args() args: CreateTeacherArgs
  ): Promise<Teacher> {
    return await this.service.createTeacher({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Teacher)
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "update",
    possession: "any",
  })
  async updateTeacher(
    @graphql.Args() args: UpdateTeacherArgs
  ): Promise<Teacher | null> {
    try {
      return await this.service.updateTeacher({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Teacher)
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "delete",
    possession: "any",
  })
  async deleteTeacher(
    @graphql.Args() args: DeleteTeacherArgs
  ): Promise<Teacher | null> {
    try {
      return await this.service.deleteTeacher(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Teacher)
  async uploadProfilePicture(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: TeacherFindUniqueArgs
  ): Promise<Teacher> {
    return await this.service.uploadProfilePicture(args, file);
  }

  @graphql.Mutation(() => Teacher)
  async deleteProfilePicture(
    @graphql.Args()
    args: TeacherFindUniqueArgs
  ): Promise<Teacher> {
    return await this.service.deleteProfilePicture(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Student], { name: "students" })
  @nestAccessControl.UseRoles({
    resource: "Student",
    action: "read",
    possession: "any",
  })
  async findStudents(
    @graphql.Parent() parent: Teacher,
    @graphql.Args() args: StudentFindManyArgs
  ): Promise<Student[]> {
    const results = await this.service.findStudents(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
